"""
report_generator.py
Generates Markdown and CSV inspection reports.
"""

import pandas as pd
from datetime import date
import os


def generate_markdown_report(engine, results: list, output_path: str) -> str:
    stats = engine.summary_stats(results)
    df    = engine.results_to_dataframe(results)
    today = date.today().isoformat()

    disp_emoji = {"PASS": "✅", "FAIL": "❌", "MRB REVIEW": "⚠️"}

    lines = [
        f"# GD&T Inspection Report — {engine.part_number}",
        f"",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| Part Number | {engine.part_number} |",
        f"| Part Name | {engine.part_name} |",
        f"| Revision | {engine.revision} |",
        f"| Supplier | {engine.supplier} |",
        f"| Report Date | {today} |",
        f"| Lots Inspected | {', '.join(sorted(stats['lots_inspected']))} |",
        f"| Parts Inspected | {stats['total_parts']} |",
        f"",
        f"---",
        f"",
        f"## Summary",
        f"",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Parts Passed | {stats['passed']} / {stats['total_parts']} ({stats['part_fpy_pct']}%) |",
        f"| Parts Failed | {stats['failed']} |",
        f"| MRB Review | {stats['mrb_review']} |",
        f"| Feature-level FPY | {stats['feature_fpy_pct']}% |",
        f"| Most Failed Feature | {stats['worst_feature']} |",
        f"",
        f"---",
        f"",
        f"## Part-Level Results",
        f"",
        f"| Serial # | Lot | Disposition | Critical Fails | Non-Crit Fails | Borderline |",
        f"|----------|-----|-------------|---------------|----------------|------------|",
    ]

    for part in results:
        emoji = disp_emoji.get(part.disposition, "")
        lines.append(
            f"| {part.part_serial_number} | {part.lot_number} | "
            f"{emoji} {part.disposition} | {len(part.critical_failures)} | "
            f"{len(part.non_critical_failures)} | {len(part.borderline_items)} |"
        )

    lines += [
        f"",
        f"---",
        f"",
        f"## Feature-Level Pass/Fail Summary",
        f"",
    ]

    feat_summary = (
        df.groupby(["feature_id","feature_name","gdandt_type","criticality","tolerance"])
        .agg(
            total=("result","count"),
            passed=("result", lambda x: (x=="PASS").sum()),
            failed=("result", lambda x: (x=="FAIL").sum()),
            borderline=("result", lambda x: (x=="BORDERLINE").sum()),
            avg_deviation=("deviation","mean"),
        )
        .round(4)
        .reset_index()
    )
    feat_summary["fpy"] = (feat_summary["passed"] / feat_summary["total"] * 100).round(1)
    feat_summary = feat_summary.sort_values("failed", ascending=False)

    lines.append(
        "| Feature | Type | Criticality | Tol | Pass | Fail | Borderline | FPY% | Avg Dev |"
    )
    lines.append(
        "|---------|------|-------------|-----|------|------|------------|------|---------|"
    )
    for _, row in feat_summary.iterrows():
        flag = "🔴" if row["failed"] > 0 else ("🟡" if row["borderline"] > 0 else "🟢")
        lines.append(
            f"| {flag} {row['feature_name']} | {row['gdandt_type']} | {row['criticality']} | "
            f"{row['tolerance']} | {row['passed']} | {row['failed']} | "
            f"{row['borderline']} | {row['fpy']}% | {row['avg_deviation']} |"
        )

    lines += [
        f"",
        f"---",
        f"",
        f"## Failed Features — Detail",
        f"",
    ]

    failed_df = df[df["result"] == "FAIL"].copy()
    if failed_df.empty:
        lines.append("_No failures detected._")
    else:
        lines.append(
            "| Serial # | Lot | Feature | Measured | Tolerance | Deviation | Margin |"
        )
        lines.append(
            "|----------|-----|---------|----------|-----------|-----------|--------|"
        )
        for _, row in failed_df.iterrows():
            lines.append(
                f"| {row['part_serial_number']} | {row['lot_number']} | "
                f"{row['feature_name']} | {row['measured_value']} | "
                f"±{row['tolerance']} | {row['deviation']} | {row['margin']} |"
            )

    lines += ["", "---", "", "_Report generated by GD&T Inspection System v1.0_"]

    content = "\n".join(lines)
    with open(output_path, "w") as f:
        f.write(content)
    return content


def generate_csv_report(engine, results: list, output_path: str) -> pd.DataFrame:
    df = engine.results_to_dataframe(results)
    df.to_csv(output_path, index=False)
    return df