"""
report_generator.py — NCR/CAPA System
Generates NCR report, CAPA report, and 8D report as Markdown strings.
"""

from datetime import date


def ncr_report(ncr: dict) -> str:
    lines = [
        f"# Non-Conformance Report",
        f"",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| NCR ID | **{ncr.get('ncr_id','')}** |",
        f"| Date Opened | {ncr.get('date_opened','')} |",
        f"| Status | {ncr.get('status','')} |",
        f"| Severity | {ncr.get('severity','')} |",
        f"| Part Number | {ncr.get('part_number','')} |",
        f"| Part Name | {ncr.get('part_name','')} |",
        f"| Serial / Lot | {ncr.get('serial_number','')} / {ncr.get('lot_number','')} |",
        f"| Supplier | {ncr.get('supplier_name','')} |",
        f"| Detected At | {ncr.get('detected_at','')} |",
        f"| Defect Type | {ncr.get('defect_type','')} |",
        f"| Qty Affected | {ncr.get('quantity_affected','')} |",
        f"| Owner | {ncr.get('owner','')} |",
        f"| Due Date | {ncr.get('due_date','')} |",
        f"| Disposition | {ncr.get('disposition','')} |",
        f"| Linked CAPA | {ncr.get('linked_capa_id','—')} |",
        f"",
        f"---",
        f"",
        f"## Defect Description",
        f"",
        f"{ncr.get('defect_description','—')}",
        f"",
        f"## Requirement",
        f"",
        f"{ncr.get('requirement','—')}",
        f"",
        f"## Actual Result",
        f"",
        f"{ncr.get('actual_result','—')}",
        f"",
        f"## Disposition Notes",
        f"",
        f"{ncr.get('disposition_notes','—')}",
        f"",
        f"---",
        f"*Generated {date.today().isoformat()} — Drone Manufacturing Quality System*",
    ]
    return "\n".join(lines)


def capa_report(capa: dict, ncr: dict = None) -> str:
    lines = [
        f"# Corrective and Preventive Action (CAPA) Report",
        f"",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| CAPA ID | **{capa.get('capa_id','')}** |",
        f"| Linked NCR | {capa.get('linked_ncr_id','—')} |",
        f"| Date Created | {capa.get('date_created','')} |",
        f"| Owner | {capa.get('action_owner','')} |",
        f"| Due Date | {capa.get('due_date','')} |",
        f"| Status | {capa.get('closure_status','')} |",
        f"| Verification Method | {capa.get('verification_method','—')} |",
        f"",
        f"---",
        f"",
        f"## Problem Statement",
        f"",
        f"{capa.get('problem_statement','—')}",
        f"",
        f"## Containment Action",
        f"",
        f"{capa.get('containment_action','—')}",
        f"",
        f"## Root Cause",
        f"",
        f"{capa.get('root_cause','—')}",
        f"",
        f"## Corrective Action",
        f"",
        f"{capa.get('corrective_action','—')}",
        f"",
        f"## Preventive Action",
        f"",
        f"{capa.get('preventive_action','—')}",
        f"",
        f"## Verification Result",
        f"",
        f"{capa.get('verification_result','—')}",
        f"",
        f"---",
        f"*Generated {date.today().isoformat()} — Drone Manufacturing Quality System*",
    ]
    return "\n".join(lines)


def eight_d_report(capa: dict, ncr: dict = None) -> str:
    part = ncr.get("part_number","—") if ncr else "—"
    supplier = ncr.get("supplier_name","—") if ncr else "—"
    defect = ncr.get("defect_type","—") if ncr else "—"

    lines = [
        f"# 8D Problem Solving Report",
        f"",
        f"**CAPA ID:** {capa.get('capa_id','—')}  ",
        f"**NCR ID:** {capa.get('linked_ncr_id','—')}  ",
        f"**Part:** {part}  ",
        f"**Supplier:** {supplier}  ",
        f"**Date:** {date.today().isoformat()}",
        f"",
        f"---",
        f"",
        f"## D1 — Team",
        f"",
        f"| Role | Name |",
        f"|------|------|",
        f"| Quality Engineer (Lead) | {capa.get('action_owner','—')} |",
        f"| Supplier Quality | QE-Patel |",
        f"| Manufacturing Engineering | ME-Rodriguez |",
        f"| Production Supervisor | PS-Williams |",
        f"| Design Engineering | DE-Kim |",
        f"",
        f"---",
        f"",
        f"## D2 — Problem Description",
        f"",
        f"{capa.get('problem_statement', '—')}",
        f"",
        f"**Defect Type:** {defect}  ",
        f"**Detected At:** {ncr.get('detected_at','—') if ncr else '—'}  ",
        f"**Severity:** {ncr.get('severity','—') if ncr else '—'}  ",
        f"**Quantity Affected:** {ncr.get('quantity_affected','—') if ncr else '—'}",
        f"",
        f"---",
        f"",
        f"## D3 — Interim Containment Action",
        f"",
        f"{capa.get('containment_action','—')}",
        f"",
        f"---",
        f"",
        f"## D4 — Root Cause Analysis",
        f"",
        f"### 5-Why Analysis",
        f"",
        f"| Step | Why |",
        f"|------|-----|",
        f"| Why 1 | {capa.get('five_why_1','—')} |",
        f"| Why 2 | {capa.get('five_why_2','—')} |",
        f"| Why 3 | {capa.get('five_why_3','—')} |",
        f"| Why 4 | {capa.get('five_why_4','—')} |",
        f"| Why 5 | {capa.get('five_why_5','—')} |",
        f"| **Root Cause** | **{capa.get('five_why_root_cause','—')}** |",
        f"",
        f"### Fishbone Contributing Factors",
        f"",
        f"| Category | Contributing Factor |",
        f"|----------|-------------------|",
        f"| Manpower | {capa.get('fishbone_manpower','—')} |",
        f"| Machine | {capa.get('fishbone_machine','—')} |",
        f"| Method | {capa.get('fishbone_method','—')} |",
        f"| Material | {capa.get('fishbone_material','—')} |",
        f"| Measurement | {capa.get('fishbone_measurement','—')} |",
        f"| Environment | {capa.get('fishbone_environment','—')} |",
        f"",
        f"---",
        f"",
        f"## D5 — Permanent Corrective Action",
        f"",
        f"{capa.get('corrective_action','—')}",
        f"",
        f"---",
        f"",
        f"## D6 — Implement Corrective Action",
        f"",
        f"**Owner:** {capa.get('action_owner','—')}  ",
        f"**Due Date:** {capa.get('due_date','—')}  ",
        f"**Status:** {capa.get('closure_status','—')}",
        f"",
        f"---",
        f"",
        f"## D7 — Prevent Recurrence",
        f"",
        f"{capa.get('preventive_action','—')}",
        f"",
        f"---",
        f"",
        f"## D8 — Closure and Team Recognition",
        f"",
        f"**Verification Method:** {capa.get('verification_method','—')}  ",
        f"**Verification Result:** {capa.get('verification_result','—')}  ",
        f"**Effectiveness Check Date:** {capa.get('effectiveness_check_date','—')}  ",
        f"**Final Status:** {capa.get('closure_status','—')}",
        f"",
        f"---",
        f"*8D Report generated {date.today().isoformat()} — Drone Manufacturing Quality System*",
    ]
    return "\n".join(lines)